---
-   name: Install dependencies
    apt:
        name:
            - apt-transport-https
            - ca-certificates
            - curl
            - software-properties-common
        state: present
        update_cache: yes

-   name: Add GPG key
    apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

-   name: Verify fingerprint
    apt_key:
        id: 0EBFCD88
        state: present

-   name: Set up the repository
    apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present
        update_cache: yes

-   name: Update apt packages
    apt:
      update_cache: yes

-   name: Install Docker
    apt:
        name: docker-ce
        state: present
        update_cache: yes
    notify: Start docker on boot

-   name: Install Docker Compose
    get_url:
        url: https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
        dest: /usr/local/bin/docker-compose
        force: true
        group: docker
        mode: 'u+x,g+x'

-   name: Set periodic Docker prune
    cron:
        name: docker-prune
        job: 'docker system prune -af --filter until=120h'
        minute: '0'
        hour: '1'

-   name: Remove useless packages
    apt:
        autoclean: yes

-   name: Remove useless dependencies
    apt:
        autoremove: yes
