import { defineStore } from "pinia";
export const useEmployeeStore = defineStore("EmployeeStore", {
  state: () => ({
    empls: [
      {
        id: 1,
        hide: true,
        thumbnail: true,
        gender: "m",
        first_name: "Герман",
        last_name: "Александров",
        middle_name: "Евгеньевич",
        birthday: "25.01",
        email: "hermansochi@ya.ru",
        telephone: "6677",
        mobile: "9899001010",
        title: "Web developer",
        department: "Dream team",
        company: "Looking for a job",
        city: "Сочи",
      },
      {
        id: 2,
        hide: false,
        thumbnail: true,
        gender: "f",
        first_name: "Клеопатра",
        last_name: "Ивановна",
        middle_name: "Романова",
        birthday: "0202",
        email: "K.Romanova@ya.ru",
        telephone: "2222",
        mobile: "92222222222",
        title: "doctor",
        department: "Dream team",
        company: "Looking for a job",
        city: "Сочи",
      },
    ],
  }),
});
